### PR TITLE
Update StopStartVMsInParallel.ps1

### PR DESCRIPTION
**Pull request by bhawna121**
Updated runbook with managed identity instead of run as account and removed classic VMs

### CODE REVIEW

**Comment by krmanupa** [comment]
could you please update the read me if required?

**Comment by krmanupa** [comment]
are the changes tested?

**Comment by krmanupa** [comment]
could you take suscriptionid as one of the parameters and have the context set as iyad had done for other runbooks. reference PR: https://github.com/azureautomation/suspend_resume_pbiembedded-by-single-resource/pull/2/files

**Comment by bhawna121** [comment]
> are the changes tested?

Yes, i had it tested in my lab

**Comment by bhawna121** [comment]
> could you please update the read me if required?

Done

**Comment by bhawna121** [comment]
> could you take suscriptionid as one of the parameters and have the context set as iyad had done for other runbooks. reference PR: https://github.com/azureautomation/suspend_resume_pbiembedded-by-single-resource/pull/2/files

Done

**Pull request merged**
